image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Build started"
    - npm install
    - npm run prettier
    # TODO: Add jobs to make this test if the server works
    - echo "Build complete"
